version: '3.9'

services:
  # web:
  #   build: .
  #   ports:
  #     - "8082:9090"
  #     - "8081:8081"
  #   depends_on:
  #     - postgres
  #     - minio

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - /root/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    restart: always

  minio:
    container_name: minio
    image:  minio/minio:RELEASE.2020-12-03T00-03-10Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data
    restart: always
  
  GeoIP:
    container_name: geoip
    image: maxmindinc/geoipupdate
    volumes:
      - .:/usr/share/GeoIP
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=637421
      - GEOIPUPDATE_LICENSE_KEY=KzrQksfB8k1PfRBU
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=5
    restart: always