// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "xiayoushuang",
            "email": "york-xia@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/application/domain": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建域名管理",
                "tags": [
                    "应用管理 - 域名管理"
                ],
                "summary": "创建域名",
                "parameters": [
                    {
                        "description": "DomainReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.DomainReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建域名成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/application/domain/multi": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "批量删除域名管理信息",
                "tags": [
                    "应用管理 - 域名管理"
                ],
                "summary": "批量删除域名管理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名管理ids, ` + "`" + `,` + "`" + `连接",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量删除域名成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/application/domain/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询域名信息",
                "tags": [
                    "应用管理 - 域名管理"
                ],
                "summary": "查询域名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名管理id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询域名成功",
                        "schema": {
                            "$ref": "#/definitions/vo.DomainResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改域名管理信息",
                "tags": [
                    "应用管理 - 域名管理"
                ],
                "summary": "修改域名管理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名管理id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "DomainUpdateReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.DomainUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改域名成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除域名管理信息",
                "tags": [
                    "应用管理 - 域名管理"
                ],
                "summary": "删除域名管理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "域名管理id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除域名成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/application/domains": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询域名管理列表",
                "tags": [
                    "应用管理 - 域名管理"
                ],
                "summary": "查询域名列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请求页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keywords",
                        "name": "keywords",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询域名列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.DataPagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/vo.DomainResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/role": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建角色",
                "tags": [
                    "权限管理 - 管理组"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "RoleReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.RoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建角色成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/role/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询角色信息",
                "tags": [
                    "权限管理 - 管理组"
                ],
                "summary": "查询角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询角色成功",
                        "schema": {
                            "$ref": "#/definitions/vo.RoleResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改角色信息",
                "tags": [
                    "权限管理 - 管理组"
                ],
                "summary": "修改角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "RoleUpdateReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.RoleUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改角色成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除角色",
                "tags": [
                    "权限管理 - 管理组"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "角色id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除角色成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询角色列表信息",
                "tags": [
                    "权限管理 - 管理组"
                ],
                "summary": "查询角色列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请求页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keywords",
                        "name": "keywords",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询角色列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.DataPagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/vo.RoleResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/rule": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建权限规则",
                "tags": [
                    "权限管理 - 权限规则"
                ],
                "summary": "创建权限规则",
                "parameters": [
                    {
                        "description": "PermissionReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.PermissionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建权限规则成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/rule/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取权限规则",
                "tags": [
                    "权限管理 - 权限规则"
                ],
                "summary": "获取权限规则",
                "parameters": [
                    {
                        "type": "string",
                        "description": "权限规则id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询权限规则成功",
                        "schema": {
                            "$ref": "#/definitions/vo.PermissionResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改权限规则",
                "tags": [
                    "权限管理 - 权限规则"
                ],
                "summary": "修改权限规则",
                "parameters": [
                    {
                        "type": "string",
                        "description": "权限规则id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PermissionUpdateReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.PermissionUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改权限规则成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除权限规则",
                "tags": [
                    "权限管理 - 权限规则"
                ],
                "summary": "删除权限规则",
                "parameters": [
                    {
                        "type": "string",
                        "description": "权限规则id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除权限规则成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/rules": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取权限规则树",
                "tags": [
                    "权限管理 - 权限规则"
                ],
                "summary": "获取权限规则树",
                "responses": {
                    "200": {
                        "description": "查询权限规则成功",
                        "schema": {
                            "$ref": "#/definitions/vo.PermissionTree"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/user": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建用户",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "UserReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建用户成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/user/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "登录用户信息",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "获取登录用户的信息",
                "responses": {
                    "200": {
                        "description": "获取用户信息成功",
                        "schema": {
                            "$ref": "#/definitions/vo.ProfileResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/user/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询用户信息",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询用户成功",
                        "schema": {
                            "$ref": "#/definitions/vo.ProfileResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改用户",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "修改用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserUpdateReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改用户成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除用户",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除用户成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/user/{id}/roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询用户角色信息",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "查询用户角色信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询用户角色信息成功",
                        "schema": {
                            "$ref": "#/definitions/vo.RoleBriefResp"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改角色权限",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "修改用户角色权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserUpdateRolesReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.UserUpdateRolesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改用户成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/permission/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询用户列表信息",
                "tags": [
                    "权限管理 - 管理员"
                ],
                "summary": "查询用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请求页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keywords",
                        "name": "keywords",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询用户列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vo.DataPagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/vo.UserResp"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "用户登录",
                "tags": [
                    "登录"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "LoginReq",
                        "name": "parameters",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vo.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "响应成功",
                        "schema": {
                            "$ref": "#/definitions/vo.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "get": {
                "description": "用户登出",
                "tags": [
                    "登录"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "响应成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "401": {
                        "description": "当前用户登录令牌失效",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "403": {
                        "description": "当前操作无权限",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vo.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "vo.DataPagination": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据"
                },
                "pagination": {
                    "description": "分页信息",
                    "$ref": "#/definitions/vo.Pagination"
                }
            }
        },
        "vo.DomainReq": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "证书",
                    "type": "string"
                },
                "domain": {
                    "description": "域名",
                    "type": "string"
                },
                "secret_key": {
                    "description": "秘钥",
                    "type": "string"
                },
                "ssl": {
                    "description": "ssl",
                    "type": "boolean"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "vo.DomainResp": {
            "type": "object",
            "properties": {
                "certificate": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "secret_key": {
                    "type": "string"
                },
                "ssl": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "vo.DomainUpdateReq": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "证书",
                    "type": "string"
                },
                "domain": {
                    "description": "域名",
                    "type": "string"
                },
                "secret_key": {
                    "description": "秘钥",
                    "type": "string"
                },
                "ssl": {
                    "description": "ssl",
                    "type": "boolean"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "vo.Error": {
            "type": "object",
            "properties": {
                "args": {
                    "description": "参数",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "description": "错误码",
                    "type": "integer"
                },
                "msg": {
                    "description": "错误消息",
                    "type": "string"
                }
            }
        },
        "vo.LoginReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "vo.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "token",
                    "type": "string"
                },
                "expiry": {
                    "description": "token 到期时间 默认两小时",
                    "type": "integer"
                },
                "token_type": {
                    "description": "认证类型",
                    "type": "string"
                }
            }
        },
        "vo.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "请求页",
                    "type": "integer"
                },
                "page_size": {
                    "description": "页大小",
                    "type": "integer"
                },
                "total_count": {
                    "description": "数据总条数",
                    "type": "integer"
                }
            }
        },
        "vo.PermissionReq": {
            "type": "object",
            "properties": {
                "identify": {
                    "description": "权限标识",
                    "type": "string"
                },
                "menu_name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级菜单的ID,最高级为 0",
                    "type": "integer"
                },
                "route": {
                    "description": "路由",
                    "type": "string"
                },
                "type": {
                    "description": "权限类型   0: 菜单权限 1: 操作权限",
                    "type": "integer"
                }
            }
        },
        "vo.PermissionResp": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "identify": {
                    "description": "权限标识",
                    "type": "string"
                },
                "index": {
                    "description": "索引",
                    "type": "integer"
                },
                "menu_name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级菜单的ID,最高级为 0",
                    "type": "integer"
                },
                "route": {
                    "description": "路由",
                    "type": "string"
                },
                "type": {
                    "description": "权限类型   0: 菜单权限 1: 操作权限",
                    "type": "integer"
                }
            }
        },
        "vo.PermissionTree": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "index": {
                    "description": "索引",
                    "type": "integer"
                },
                "menu_name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级ID",
                    "type": "integer"
                },
                "route": {
                    "description": "路由",
                    "type": "string"
                },
                "sub_permissions": {
                    "description": "子级权限",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.PermissionTree"
                    }
                }
            }
        },
        "vo.PermissionUpdateReq": {
            "type": "object",
            "properties": {
                "identify": {
                    "description": "权限标识",
                    "type": "string"
                },
                "index": {
                    "description": "索引",
                    "type": "integer"
                },
                "menu_name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "parent_id": {
                    "description": "父级菜单的ID,最高级为 0",
                    "type": "integer"
                },
                "route": {
                    "description": "路由",
                    "type": "string"
                },
                "type": {
                    "description": "权限类型   0: 菜单权限 1: 操作权限",
                    "type": "integer"
                }
            }
        },
        "vo.ProfileResp": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "vo.RoleBriefResp": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "角色ID",
                    "type": "integer"
                },
                "name": {
                    "description": "角色命",
                    "type": "string"
                }
            }
        },
        "vo.RoleReq": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "说明",
                    "type": "string"
                },
                "identify": {
                    "description": "标识符",
                    "type": "string"
                },
                "name": {
                    "description": "角色命",
                    "type": "string"
                },
                "permission": {
                    "description": "权限ids",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.RoleResp": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "说明",
                    "type": "string"
                },
                "id": {
                    "description": "角色ID",
                    "type": "integer"
                },
                "identify": {
                    "description": "标识符",
                    "type": "string"
                },
                "name": {
                    "description": "角色命",
                    "type": "string"
                },
                "permissions": {
                    "description": "权限",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.RoleUpdateReq": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "说明",
                    "type": "string"
                },
                "identify": {
                    "description": "标识符",
                    "type": "string"
                },
                "name": {
                    "description": "角色命",
                    "type": "string"
                },
                "permission": {
                    "description": "权限ids",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "vo.UserReq": {
            "type": "object",
            "properties": {
                "is_admin": {
                    "description": "是否管理员",
                    "type": "boolean"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "vo.UserResp": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "vo.UserUpdateReq": {
            "type": "object",
            "properties": {
                "is_admin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "vo.UserUpdateRolesReq": {
            "type": "object",
            "properties": {
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{"http", "https"},
	Title:       "JS流量统计管理系统后台API",
	Description: "JS流量统计管理系统后台API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
