basePath: /
definitions:
  vo.DataPagination:
    properties:
      data:
        description: 数据
      pagination:
        $ref: '#/definitions/vo.Pagination'
        description: 分页信息
    type: object
  vo.Error:
    properties:
      args:
        description: 参数
        items:
          type: string
        type: array
      code:
        description: 错误码
        type: integer
      msg:
        description: 错误消息
        type: string
    type: object
  vo.LoginReq:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  vo.LoginResponse:
    properties:
      access_token:
        description: token
        type: string
      expiry:
        description: token 到期时间 默认两小时
        type: integer
      token_type:
        description: 认证类型
        type: string
    type: object
  vo.Pagination:
    properties:
      page:
        description: 请求页
        type: integer
      page_size:
        description: 页大小
        type: integer
      total_count:
        description: 数据总条数
        type: integer
    type: object
  vo.PermissionReq:
    properties:
      identify:
        description: 权限标识
        type: string
      menu_name:
        description: 菜单名称
        type: string
      name:
        description: 名称
        type: string
      parent_id:
        description: 父级菜单的ID,最高级为 0
        type: integer
      route:
        description: 路由
        type: string
      type:
        description: '权限类型   0: 菜单权限 1: 操作权限'
        type: integer
    type: object
  vo.PermissionResp:
    properties:
      id:
        description: ID
        type: integer
      identify:
        description: 权限标识
        type: string
      index:
        description: 索引
        type: integer
      menu_name:
        description: 菜单名称
        type: string
      name:
        description: 名称
        type: string
      parent_id:
        description: 父级菜单的ID,最高级为 0
        type: integer
      route:
        description: 路由
        type: string
      type:
        description: '权限类型   0: 菜单权限 1: 操作权限'
        type: integer
    type: object
  vo.PermissionTree:
    properties:
      id:
        description: ID
        type: integer
      index:
        description: 索引
        type: integer
      menu_name:
        description: 菜单名称
        type: string
      name:
        description: 名称
        type: string
      parent_id:
        description: 父级ID
        type: integer
      route:
        description: 路由
        type: string
      sub_permissions:
        description: 子级权限
        items:
          $ref: '#/definitions/vo.PermissionTree'
        type: array
    type: object
  vo.PermissionUpdateReq:
    properties:
      identify:
        description: 权限标识
        type: string
      index:
        description: 索引
        type: integer
      menu_name:
        description: 菜单名称
        type: string
      name:
        description: 名称
        type: string
      parent_id:
        description: 父级菜单的ID,最高级为 0
        type: integer
      route:
        description: 路由
        type: string
      type:
        description: '权限类型   0: 菜单权限 1: 操作权限'
        type: integer
    type: object
  vo.ProfileResp:
    properties:
      admin:
        type: boolean
      id:
        type: integer
      name:
        type: string
    type: object
  vo.RoleReq:
    properties:
      description:
        description: 说明
        type: string
      identify:
        description: 标识符
        type: string
      name:
        description: 角色命
        type: string
      permission:
        description: 权限ids
        items:
          type: integer
        type: array
    type: object
  vo.RoleResp:
    properties:
      description:
        description: 说明
        type: string
      id:
        description: 角色ID
        type: integer
      identify:
        description: 标识符
        type: string
      name:
        description: 角色命
        type: string
      permissions:
        description: 权限
        items:
          type: integer
        type: array
    type: object
  vo.RoleUpdateReq:
    properties:
      description:
        description: 说明
        type: string
      identify:
        description: 标识符
        type: string
      name:
        description: 角色命
        type: string
      permission:
        description: 权限ids
        items:
          type: integer
        type: array
    type: object
  vo.UserReq:
    properties:
      is_admin:
        type: boolean
      password:
        type: string
      user_name:
        type: string
    type: object
  vo.UserUpdateReq:
    properties:
      is_admin:
        type: boolean
      password:
        type: string
      user_name:
        type: string
    type: object
info:
  contact:
    email: york-xia@gmail.com
    name: xiayoushuang
  description: JS流量统计管理系统后台API
  title: JS流量统计管理系统后台API
  version: "1.0"
paths:
  /api/v1/permission/role:
    post:
      description: 创建角色
      parameters:
      - description: RoleReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.RoleReq'
      responses:
        "200":
          description: 创建角色成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 创建角色
      tags:
      - 权限管理 - 管理组
  /api/v1/permission/role/{id}:
    delete:
      description: 删除角色
      parameters:
      - description: 角色id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 删除角色成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - 权限管理 - 管理组
    get:
      description: 查询角色信息
      parameters:
      - description: 角色id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 查询角色成功
          schema:
            $ref: '#/definitions/vo.RoleResp'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 查询角色
      tags:
      - 权限管理 - 管理组
    put:
      description: 修改角色信息
      parameters:
      - description: 角色id
        in: path
        name: id
        required: true
        type: string
      - description: RoleUpdateReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.RoleUpdateReq'
      responses:
        "200":
          description: 修改角色成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 修改角色
      tags:
      - 权限管理 - 管理组
  /api/v1/permission/roles:
    get:
      description: 查询角色列表信息
      parameters:
      - description: 请求页
        in: query
        name: page
        type: integer
      - description: 页大小
        in: query
        name: page_size
        type: integer
      - description: keywords
        in: query
        name: keywords
        type: string
      responses:
        "200":
          description: 查询角色列表成功
          schema:
            allOf:
            - $ref: '#/definitions/vo.DataPagination'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/vo.RoleResp'
                  type: array
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 查询角色列表
      tags:
      - 权限管理 - 管理组
  /api/v1/permission/rule:
    post:
      description: 创建权限规则
      parameters:
      - description: PermissionReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.PermissionReq'
      responses:
        "200":
          description: 创建权限规则成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 创建权限规则
      tags:
      - 权限管理 - 权限规则
  /api/v1/permission/rule/{id}:
    delete:
      description: 删除权限规则
      parameters:
      - description: 权限规则id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 删除权限规则成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 删除权限规则
      tags:
      - 权限管理 - 权限规则
    get:
      description: 获取权限规则
      parameters:
      - description: 权限规则id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 查询权限规则成功
          schema:
            $ref: '#/definitions/vo.PermissionResp'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 获取权限规则
      tags:
      - 权限管理 - 权限规则
    put:
      description: 修改权限规则
      parameters:
      - description: 权限规则id
        in: path
        name: id
        required: true
        type: string
      - description: PermissionUpdateReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.PermissionUpdateReq'
      responses:
        "200":
          description: 修改权限规则成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 修改权限规则
      tags:
      - 权限管理 - 权限规则
  /api/v1/permission/rules:
    get:
      description: 获取权限规则树
      responses:
        "200":
          description: 查询权限规则成功
          schema:
            $ref: '#/definitions/vo.PermissionTree'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 获取权限规则树
      tags:
      - 权限管理 - 权限规则
  /api/v1/permission/user:
    post:
      description: 创建用户
      parameters:
      - description: UserReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.UserReq'
      responses:
        "200":
          description: 创建用户成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 创建用户
      tags:
      - 权限管理 - 管理员
  /api/v1/permission/user/{id}:
    get:
      description: 查询用户信息
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: 查询用户成功
          schema:
            $ref: '#/definitions/vo.ProfileResp'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 查询用户
      tags:
      - 权限管理 - 管理员
    put:
      description: 修改用户
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      - description: UserUpdateReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.UserUpdateReq'
      responses:
        "200":
          description: 修改用户成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 修改用户
      tags:
      - 权限管理 - 管理员
  /api/v1/permission/user/profile:
    get:
      description: 登录用户信息
      responses:
        "200":
          description: 获取用户信息成功
          schema:
            $ref: '#/definitions/vo.ProfileResp'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      security:
      - ApiKeyAuth: []
      summary: 获取登录用户的信息
      tags:
      - 权限管理 - 管理员
  /auth/login:
    post:
      description: 用户登录
      parameters:
      - description: LoginReq
        in: body
        name: parameters
        required: true
        schema:
          $ref: '#/definitions/vo.LoginReq'
      responses:
        "200":
          description: 响应成功
          schema:
            $ref: '#/definitions/vo.LoginResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      summary: 用户登录
      tags:
      - 登录
  /auth/logout:
    get:
      description: 用户登出
      responses:
        "200":
          description: 响应成功
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/vo.Error'
        "401":
          description: 当前用户登录令牌失效
          schema:
            $ref: '#/definitions/vo.Error'
        "403":
          description: 当前操作无权限
          schema:
            $ref: '#/definitions/vo.Error'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/vo.Error'
      summary: 用户登出
      tags:
      - 登录
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
